### ISSUE TITLE
中文化

### ISSUE THREAD

**Issue by pm5** [lowiki-org/localwiki-backend-server#12]
這個 issue 用來搜集平台中文化需求。LocalWiki 本身有中文化的架構，不過已經翻成中文的訊息好像很少。

- 一定要翻成中文的訊息有哪些？
- 最好可以翻成中文的有哪些？

**Comment by pm5** [comment]
更新 mo 檔的方式（在 VM 裡）：
```
$ source /srv/localwiki/env/bin/activate
$ sudo -u www-data localwiki-manage compilemessages
```

**Comment by Superbil** [comment]
更新可以使用寫好的 script `fab vagrant pull_translations`
