### ISSUE TITLE
測試 VisualEditor

### ISSUE THREAD

**Issue by pm5** [lowiki-org/localwiki-backend-server#17]
* [ ] https://github.com/wikimedia/VisualEditor 跑起來看看
  - 能不能 render wiki text（包含 template 語法）
  - 怎麼包進 Django application 裡

**Comment by Superbil** [comment]
Wikimedia 使用的轉換引擎 https://www.mediawiki.org/wiki/Parsoid

**Comment by pm5** [comment]
大概無法做。先關掉了。
