### ISSUE TITLE
更換後端儲存資料格式成 parsoid

### ISSUE THREAD

**Issue by Superbil** [lowiki-org/localwiki-backend-server#20]
使用跟 Wikimedia 相同的資料格式，使用 [Parsoid](https://www.mediawiki.org/wiki/Parsoid)

**Comment by Superbil** [comment]
這個跟 #18 有關

**Comment by Superbil** [comment]
Parsoid 需要 mediawiki 的 [API](https://en.wikipedia.org/w/api.php)
[Parsoid 主要的流程](https://wikitech.wikimedia.org/wiki/Parsoid#Data_flow)

**Comment by pm5** [comment]
大概無法做。先關掉了。
