### ISSUE TITLE
加標籤的時候自動插入模板語法

### ISSUE THREAD

**Issue by pm5** [lowiki-org/localwiki-backend-server#31]
例如，加「社區」標籤的時候，同時在頁面最前端加進 `{{社區}}` 語法，含模板範例。

**Comment by pm5** [comment]
@Superbil 我是覺得在[這裡](https://github.com/lowiki-org/localwiki-backend-server/blob/master/localwiki/tags/views.py#L278)加個 `form_valid` 的話你用 `form.instance` 就可以拿到 `.page` 跟 `.tags` 了？雖然副作用感覺有點大，不過不要改太多的話應該還行。

**Comment by Superbil** [comment]
已在 34104aece9612d2ce944200fffc1014b2eadd0a4 實作此功能
