### ISSUE TITLE
一些翻譯

### ISSUE THREAD

**Issue by pm5** [lowiki-org/localwiki-backend-server#45]
- 「探索」要翻什麼好？
-  搜尋框的說明也要翻譯
<img width="421" alt="screen shot 2016-09-05 at 2 44 47 pm" src="https://cloud.githubusercontent.com/assets/119645/18239362/73393596-7377-11e6-8c4d-844e6579d7ba.png">

**Comment by Superbil** [comment]
Search for 和 Search all of LocalWiki 是 djangojs 這個裡面的翻譯，但是改了並沒有看到效果

**Comment by pm5** [comment]
上次好像沒討論完。@Superbil 這個可能要請你查一查是什麼問題，因為搜尋框的中文還蠻重要的。

**Comment by pm5** [comment]
翻譯好了，但是 server 有點問題，檔案沒有更新
