### ISSUE TITLE
Redirect 「重新導向」這個功能需要更多說明

### ISSUE THREAD

**Issue by pm5** [lowiki-org/localwiki-backend-server#46]
編輯頁面時，「重新導向」讓人看不懂是什麼意思。要在點進去以後那一頁增加中文說明，說明常見的使用情境。

**Comment by Superbil** [comment]
維基使用「重新定向」這個組合

重新定向是一種特殊的頁面，它提供一種運作機制，使得人們在輸入該名稱進入條目或者點擊指向該名稱的內部連結時，系統能夠自動導航到重新定向頁面內部指定的另一相關頁面中，從而實現相關頁面可以以多個名稱進行存取。

舉例來說，如果設定了「名稱為「台北縣」」，而內容指向「新北市」的重新定向頁之後，任何人都可以用「台北縣」這一名稱進入到新北市條目中。

**Comment by Superbil** [comment]
或者是，如果設定了名稱為「高雄縣」，內容指向「高雄市」的重新定向頁之後，之後都可以用「高雄縣」這個一名稱進入到高雄市的條目中。

**Comment by pm5** [comment]
Merged in 958c98969e64a9e2b75a61c569e93c768106403e
