### ISSUE TITLE
有一些 cache 沒有清掉

### ISSUE THREAD

**Issue by pm5** [lowiki-org/localwiki-backend-server#51]
- Front_page 並沒有完全被清除掉
- 小地圖並沒有清除上一次的暫存
- WMS 圖層沒有正確顯示

**Comment by Superbil** [comment]
已有的案例
-   興得里/台北市文山運身中心
-   區域首頁的更新太慢

**Comment by pm5** [comment]
trace 了一下，區域首頁的 cache 還沒找到 cache 在哪個元件裡。不在 Django core cache 裡，也不在 johnny-cache（ORM cache）。目前最可行的方法是直接關掉 Memcached 😑

**Comment by pm5** [comment]
修好了。
