### ISSUE TITLE
在區域搜尋標籤

### ISSUE THREAD

**Issue by Superbil** [lowiki-org/localwiki-backend-server#57]
在區域搜尋標籤，下面其他相關頁面應該依距離顯示(以一公里為限)，或者是不顯示

**Comment by pm5** [comment]
看起來原本的設定查詢是 60 miles（約 90 公里）以內的點，需要改小一點的範圍。另外也有一些匯入資料有問題要修正。

**Comment by pm5** [comment]
用 1 公里半徑看起來會因為一些查詢的誤差而有時找不到資料。目前設定成大約 2 公里半徑範圍。
